update workflow

diff --git a/.github/workflows/increase-patch-version-and-tag-git-periodically.yaml b/.github/workflows/increase-patch-version-and-tag-git-periodically.yaml
--- a/.github/workflows/increase-patch-version-and-tag-git-periodically.yaml
+++ b/.github/workflows/increase-patch-version-and-tag-git-periodically.yaml
@@ -24,8 +24,17 @@ jobs:
       - name: Get latest tag
         id: get-latest-tag
         run: |
+        
           # Get the latest tag, default to v0.0.0 if no tags exist
-          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
+
+          LATEST_TAG=$(git tag -l | sort -V | tail -n 1)
+          
+          # If no tags exist, set default version
+          if [ -z "$LATEST_TAG" ]; then
+            echo "ERROR: No tags found"
+            exit 1
+            LATEST_TAG="v0.0.0"
+          fi
           echo "LATEST_TAG=${LATEST_TAG}" >> $GITHUB_ENV
           echo "Latest tag: ${LATEST_TAG}"
 
